// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.12
// source: swupdate.proto

package swupdatesvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UpdaterClient is the client API for Updater service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UpdaterClient interface {
	CheckForUpdate(ctx context.Context, in *CheckForUpdateRequest, opts ...grpc.CallOption) (*CheckForUpdateResponse, error)
	ExecuteUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (Updater_ExecuteUpdateClient, error)
	Reboot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
}

type updaterClient struct {
	cc grpc.ClientConnInterface
}

func NewUpdaterClient(cc grpc.ClientConnInterface) UpdaterClient {
	return &updaterClient{cc}
}

func (c *updaterClient) CheckForUpdate(ctx context.Context, in *CheckForUpdateRequest, opts ...grpc.CallOption) (*CheckForUpdateResponse, error) {
	out := new(CheckForUpdateResponse)
	err := c.cc.Invoke(ctx, "/swupdate.Updater/CheckForUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *updaterClient) ExecuteUpdate(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (Updater_ExecuteUpdateClient, error) {
	stream, err := c.cc.NewStream(ctx, &Updater_ServiceDesc.Streams[0], "/swupdate.Updater/ExecuteUpdate", opts...)
	if err != nil {
		return nil, err
	}
	x := &updaterExecuteUpdateClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Updater_ExecuteUpdateClient interface {
	Recv() (*UpdateResponse, error)
	grpc.ClientStream
}

type updaterExecuteUpdateClient struct {
	grpc.ClientStream
}

func (x *updaterExecuteUpdateClient) Recv() (*UpdateResponse, error) {
	m := new(UpdateResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *updaterClient) Reboot(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := c.cc.Invoke(ctx, "/swupdate.Updater/Reboot", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UpdaterServer is the server API for Updater service.
// All implementations must embed UnimplementedUpdaterServer
// for forward compatibility
type UpdaterServer interface {
	CheckForUpdate(context.Context, *CheckForUpdateRequest) (*CheckForUpdateResponse, error)
	ExecuteUpdate(*UpdateRequest, Updater_ExecuteUpdateServer) error
	Reboot(context.Context, *Empty) (*Empty, error)
	mustEmbedUnimplementedUpdaterServer()
}

// UnimplementedUpdaterServer must be embedded to have forward compatible implementations.
type UnimplementedUpdaterServer struct {
}

func (UnimplementedUpdaterServer) CheckForUpdate(context.Context, *CheckForUpdateRequest) (*CheckForUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckForUpdate not implemented")
}
func (UnimplementedUpdaterServer) ExecuteUpdate(*UpdateRequest, Updater_ExecuteUpdateServer) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteUpdate not implemented")
}
func (UnimplementedUpdaterServer) Reboot(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reboot not implemented")
}
func (UnimplementedUpdaterServer) mustEmbedUnimplementedUpdaterServer() {}

// UnsafeUpdaterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UpdaterServer will
// result in compilation errors.
type UnsafeUpdaterServer interface {
	mustEmbedUnimplementedUpdaterServer()
}

func RegisterUpdaterServer(s grpc.ServiceRegistrar, srv UpdaterServer) {
	s.RegisterService(&Updater_ServiceDesc, srv)
}

func _Updater_CheckForUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckForUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdaterServer).CheckForUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swupdate.Updater/CheckForUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdaterServer).CheckForUpdate(ctx, req.(*CheckForUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Updater_ExecuteUpdate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UpdaterServer).ExecuteUpdate(m, &updaterExecuteUpdateServer{stream})
}

type Updater_ExecuteUpdateServer interface {
	Send(*UpdateResponse) error
	grpc.ServerStream
}

type updaterExecuteUpdateServer struct {
	grpc.ServerStream
}

func (x *updaterExecuteUpdateServer) Send(m *UpdateResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _Updater_Reboot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UpdaterServer).Reboot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/swupdate.Updater/Reboot",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UpdaterServer).Reboot(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// Updater_ServiceDesc is the grpc.ServiceDesc for Updater service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Updater_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "swupdate.Updater",
	HandlerType: (*UpdaterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckForUpdate",
			Handler:    _Updater_CheckForUpdate_Handler,
		},
		{
			MethodName: "Reboot",
			Handler:    _Updater_Reboot_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteUpdate",
			Handler:       _Updater_ExecuteUpdate_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "swupdate.proto",
}
